// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

import { CONFIG } from '@/lib/config';

const SUPABASE_URL = CONFIG.SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = CONFIG.SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

/**
 * Untyped Supabase client for use with custom schemas (e.g. 'saas')
 * that are not present in the generated types.ts.
 * Use this when querying tables from the 'saas' schema.
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const supabaseSaas: ReturnType<typeof createClient> = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
}) as any;
